import type { Metadata } from 'next';
import Sidebar from '../components/sidebar';
import NavBar from '../components/navBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full">
      <Sidebar />
      <div className="flex flex-col h-full w-full ml-52 p-4 bg-white">
        <NavBar />
        <div className="mt-5 ml-1">{children}</div>
      </div>
    </div>
  );
}
